### ISSUE TITLE
I dont see the download button anywhere

### ISSUE THREAD

**Issue by SunnyBearHub** [Hans5958/mini-htmls#19]
Im using your TextureAtlas extractor, and when i do submit and everything's done i dont see any thing to download the extracted textures, do you know where that button is?

**Comment by Hans5958** [comment]
:wave: There's no download button and you only have to press the "Submit" button after choosing your files to start the process. If the extraction is successful, the result should've been automatically downloaded.

**Comment by Hans5958** [comment]
Due to inactivity, I'm going to assume that the problem is resolved, and so I will close this. Feel free to reopen if you still need it.
