### ISSUE TITLE
Why it takes so mucho?

### ISSUE THREAD

**Issue by JoelAleTop17** [Hans5958/mini-htmls#21]
When I tap submit, it says status (1/2) but it doesn't progress i'm talking about your texture separator

**Comment by Hans5958** [comment]
👋 Could you please give me the files that you give the tool?

It might be an error in my code, an error in the texture, or something unexpected, and I can't know for sure if you don't give me the files for me to try.

**Comment by Hans5958** [comment]
Due to inactivity, I have to close this. Feel free to reopen if you still need it.

**Comment by JoelAleTop17** [comment]
Hi, it was a picture of 9 MB i think that's the problem: picture is too
heavy

**Comment by Hans5958** [comment]
Are you doing this on your phone? I have no plans to support usage on the phone, by the way. #24

If it isn't, could you please give me the files for me to test?

**Comment by JoelAleTop17** [comment]
Sorry but gmail don't allow me cuz its to big

**Comment by Hans5958** [comment]
Could you upload it using GitHub? I think you should be able to login, since you have access to this email you're using.

**Comment by JoelAleTop17** [comment]
I will try that.
