### ISSUE TITLE
Bugged fnf sprite

### ISSUE THREAD

**Issue by Blip25** [Hans5958/mini-htmls#22]
Here the tests
[blaze.zip](https://github.com/user-attachments/files/16368862/blaze.zip)

**Comment by Hans5958** [comment]
👋 Welcome to the repository!

Could you please give me the files that you give the tool? I need it to reproduce the issue.

Also, what's wrong? I guess them being wrongly cropped? Could you please elaborate just so I'm sure?

**Comment by Hans5958** [comment]
Due to inactivity, I have to close this. Feel free to reopen if you still need it.
