### ISSUE TITLE
Support for rotated sprites

### ISSUE THREAD

**Issue by betasnap** [Hans5958/mini-htmls#23]
hey! i just wanted to suggest adding support for rotated spritesheets like the one shown below:
![lordX-damino](https://github.com/user-attachments/assets/037d7029-d143-4fb3-ad2d-01da9b925d8d)
i just wanted to suggest this idea since it would be nice if there were support for these kind of spritesheets because they come out all cropped

**Comment by Hans5958** [comment]
👋 Welcome to the repository!

I suppose that this is related to #22, but I have no details about it other than the initial post. Could you please give me the input files (the atlas that you gave the tool)? I need it to reproduce the issue.

**Comment by AbelitoGamer** [comment]
It seems that they died trying to send the files. Fortunately, here I have both the .png and the .xml with this rotated property.
![blaze](https://github.com/user-attachments/assets/01b5f2ae-35b0-42b6-952e-e999b60432dd)
[blaze.txt](https://github.com/user-attachments/files/18051635/blaze.txt)
(The TXT is the .xml, GitHub doesn't want to send it with the original extension.).

The only key difference I can notice is the new rotated="true" value. The rotated frames apparently are always rotated 90 degrees clockwise, or at least in the spritesheets that I've seen with this property.
