### ISSUE TITLE
spritesheet rotated

### ISSUE THREAD

**Issue by Newoplo** [Hans5958/mini-htmls#26]
so this spritesheet is rotated and the png are rotated can you fix it?
example:
![cn](https://github.com/user-attachments/assets/8599e7d6-bc97-4626-b846-a618cd39551a)

**Comment by Hans5958** [comment]
👋 This is a duplicate. Your issue has been covered on #23. I will close this to reduce clutter.

However, I still need the `.xml` or `.json` as an example. Could you give it on #23?
